project:
  type: book

book:
  title: "CCPhos Documentation"
  subtitle: "Development and Usage of dsCCPhos and dsCCPhosClient"
  author: "Bastian Reiter"
  date: last-modified
  search: true
  downloads: [pdf]
  sidebar:
    style: docked
    background: light
  chapters:
    - index.qmd
    - part: "General Info"
      chapters:
        - CCP.qmd
        - DataShield.qmd
        - CCPhos.qmd
    - part: "Using CCPhos"
      chapters: 
        - Example.qmd
        - DataModels.qmd
    - part: "Methodical Aspects"
      chapters:
        - SemanticPremises.qmd
        - DataProcessing.qmd
        - StatisticalMethods.qmd
        - LimitationsAndConcerns.qmd
    - part: "Development"
      chapters: 
        - Development.qmd
    - part: "Governance"
      chapters:
        - Governance.qmd
        - Downloads.qmd
    - part: "Publications"
      chapters:
        - Publications.qmd
    - part: "References"
      chapters:
        - References.qmd
  comments:
    hypothesis:
      theme: clean
      openSidebar: false


bibliography: references.bib
csl: nature.csl


format:
  
  html:
    code-link: true
    code-fold: true
    default-image-extension: svg
    grid:
      sidebar-width: 400px
    number-sections: false
    theme:
      - cosmo
      - theme.scss
    reference-location: margin
      

editor: source

filters:
  - lightbox
